version: "3.8"
services:
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ${DATABASE_PATH}:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}

  redis:
    image: redis:latest
    ports:
      - 6379:6379