version: "3.8"
services:

  app:
    build: .
    ports:
      - "8000:8000"
    command: daphne -b ${APP_HOST} -p ${APP_PORT} instagram.asgi:application
    volumes:
      - .:/app

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ${DATABASE_PATH}:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  worker:
    build:
      context: .
    command: "celery -A instagram worker --beat"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
