POST http://localhost:8000/login/
Content-Type: application/json

{
    "email": "yeren@test.com",
    "password": "1234"
}


###
GET http://localhost:8000/post/
Authorization: Token 40e6be31c22dbde51b4982037b71da60adb45d9f


###
POST http://localhost:8000/logout/
Authorization: Token abf70d6fdb40d09fd4f988319e5706dd048bfb93

###
POST http://localhost:8000/post/
Authorization: Token 40e6be31c22dbde51b4982037b71da60adb45d9f
Content-Type: application/json

{
    "text":"test post view"
}


###
POST https://api.example.com/user/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
