POST http://localhost:8000/login/
Content-Type: application/json

{
    "email": "yeren@test.com",
    "password": "1234"
}


###
GET http://localhost:8000/post/
Authorization: Token 40e6be31c22dbde51b4982037b71da60adb45d9f


### 
POST http://localhost:8000/logout/
Authorization: Token abf70d6fdb40d09fd4f988319e5706dd048bfb93

###
POST http://localhost:8000/post/
Authorization: Token 40e6be31c22dbde51b4982037b71da60adb45d9f
Content-Type: application/json

{
    "text":"test post view"
}


###
GET http://localhost:8000/like/
Authorization: Token 40e6be31c22dbde51b4982037b71da60adb45d9f

###
POST http://localhost:8000/like/
Authorization: Token 40e6be31c22dbde51b4982037b71da60adb45d9f
Content-Type: application/json

{
    "post": 2
}

###
POST http://localhost:8000/comment/
Authorization: Token 40e6be31c22dbde51b4982037b71da60adb45d9f
Content-Type: application/json

{
    "post": 2,
    "text": "added comment"
}


###
GET http://localhost:8000/comment/
Authorization: Token 40e6be31c22dbde51b4982037b71da60adb45d9f



###
GET http://localhost:8000/profile-stories/
Authorization: Token 40e6be31c22dbde51b4982037b71da60adb45d9f
