# Generated by Django 3.2.19 on 2023-06-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0004_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
