# Generated by Django 3.2.10 on 2022-05-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0012_publicchatroom_publicchatroommessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descrption',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
