# Generated by Django 3.2.10 on 2022-05-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0013_user_descrption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='descrption',
            new_name='description',
        ),
    ]
